import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { checkAuthentication, removeLocalStorage } from "../actions/auth";

export default function Home() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const response = async () => {
      const resjson = await checkAuthentication();
      console.log(resjson);
      if (resjson.userAuthenticated) {
        setIsAuthenticated(true);
      } else {
        router.push("/login");
      }
    };
    response();
  }, []);

  const handleLogout = () => {
    alert("are you sure want to log out");
    setIsAuthenticated(!removeLocalStorage("auth-token"));
    router.push("/login");
  };
  // useEffect(() => {
  //   const checkAuthentication = async () => {
  //     const authToken = localStorage.getItem("auth-token");
  //     const res = await fetch(`${BASE_API_URL}/getuser`, {
  //       method: "GET",
  //       headers: {
  //         "Content-Type": "application/json",
  //         "auth-token": authToken,
  //       },
  //     });
  //     const resjson = await res.json();

  //     if (resjson.userAuthenticated) {
  //       setIsAuthenticated(true);
  //     } else {
  //       router.push("/login");
  //     }
  //   };

  return (
    <>
      {isAuthenticated ? (
        <div>
          <Head>
            <title>Todo App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <div>
            <button
              className="bg-red-500 px-3 py-1 rounded-sm text-white font-semibold"
              onClick={handleLogout}
            >
              Logout
            </button>
          </div>

          <main>
            {/* Todo */}
            Create a Todo app interface, refer provided screenshots for design.
          </main>
        </div>
      ) : (
        <div>Loading.........</div>
      )}
    </>
  );
}
