import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { isAuth } from "../actions/auth";
import { useState, useEffect } from "react";
import { BASE_API_URL } from "../actions/auth";

export default function Home() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const checkAuthentication = async () => {
      const authToken = localStorage.getItem("auth-token");
      const res = await fetch(`${BASE_API_URL}/getuser`, {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          "auth-token": authToken,
        },
      });
      const resjson = await res.json();

      if (resjson.userAuthenticated) {
        setIsAuthenticated(true);
      } else {
        router.push("/login");
      }
    };
    checkAuthentication();
  }, []);

  return (
    <>
      {isAuthenticated ? (
        <div>
          <Head>
            <title>Todo App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            {/* Todo */}
            Create a Todo app interface, refer provided screenshots for design.
          </main>
        </div>
      ) : (
        <div>Loading.........</div>
      )}
    </>
  );
}
